name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!
        
        Please search [existing issues](https://github.com/ardzz/perplexity-scrape/issues) first to see if it's already been requested.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues for this feature
          required: true
        - label: I have read the contributing guidelines
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem description
      description: |
        Describe the problem you're trying to solve.
        Example: "I'm always frustrated when..."
      placeholder: I want to be able to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or features you've considered.

  - type: textarea
    id: use_cases
    attributes:
      label: Use cases
      description: Describe specific use cases where this feature would be helpful.

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, screenshots, or references.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be interested in submitting a PR for this feature
